# Generated by Django 4.0.6 on 2022-07-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('length', models.CharField(default='', max_length=50)),
                ('elevation', models.CharField(default='', max_length=50)),
                ('duration', models.CharField(default='', max_length=20)),
                ('difficulty', models.CharField(default='', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('url', models.URLField()),
                ('imageUrl', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
